import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopNav from "./_components/TopNav";
import TopHead from "./_components/TopHead";
import Footer from "./_components/Footer";
import { AuthProvider } from "../app/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Plastikit",
  description: "Generated by Koren & Roy",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider projectId="P2fBgx8H3bG5LZPtQo20GYUBd7am">
      <html lang="en">
        <body className={inter.className}>
          {/* <TopNav /> */}
          <TopHead />
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
