import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopNav from "./_components/TopNav";
import TopHead from "./_components/TopHead";
import Footer from "./_components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Plastikit",
  description: "Generated by Koren & Roy",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopNav />
        <TopHead />
        {children}
        <footer
          style={{
            border: "1px solid gray",
            display: "flex",
            height: "20vh",
            textAlign: "center",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <Footer />
        </footer>
      </body>
    </html>
  );
}
